---

- name: Clone mpid git repo
  git:
    repo: https://bitbucket.org/fayaaz_ahmed/mpid.git
    dest: /var/www/mpid
    version: dockerize

- name: Install nginx
  apt:
    name: nginx
    state: installed
    update_cache: true

- name: remove default nginx conf
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Update nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/mpid
  notify: restart nginx

- name: Ensure log folder exist
  file:
    path: /var/log/mpid/
    state: directory


- name: Ensure access and error logs exist
  file:
    path: "{{item}}"
    state: touch
  with_items:
    - /var/log/mpid/access.log
    - /var/log/mpid/error.log