---

- name: Install mpd
  apt:
    pkg: mpd
    state: installed
    update_cache: true

- name: Copy mpd conf
  copy:
    src: mpd.conf
    dest: /etc/mpd.conf
  notify: restart mpd

- name: Install mpc
  apt:
    pkg: mpc
    state: installed
    update_cache: true

- name: Install mpdscribble
  apt:
    pkg: mpdscribble
    state: installed
    update_cache: true
